### ISSUE TITLE
depencies out of date

### ISSUE THREAD

**Issue by davidmoshal** [survivejs/cerebral-demo#1]
cerebral-react and cerebral-baobab have been renamed:     

cerebral-model-baobab
cerebral-view-react

good news is that if you update the demo, you'll be able to use the interesting Cerebral Chrome extension!

Dave

**Comment by Guria** [comment]
I think you can make a PR. But it will require a little more than just updating deps.

**Comment by bebraw** [comment]
Yeah, I'll get it updated. No need for PR. :)

**Comment by Guria** [comment]
@bebraw maybe it worth to delay it until `cerebral@0.34` release. We are cleaning out lot of stuff now.

**Comment by Guria** [comment]
btw, we have new concept of modules. you can look it on http://cerebraljs.com website

**Comment by bebraw** [comment]
@Guria Alright. Poke me again after the release and I'll get the work done. Maybe that's something you can then link to. :+1:

**Comment by davidmoshal** [comment]
you might want to look at `cerebral-boilerplate` ,  it's also out of date, but is fixed with `ncu -u`. 
Also, it seems to use the more recent `react-transform-hmr`   - would be great to see these features explained in your **_excellent SurviveJS book**_!
Here is their `.babelrc`

```
{
  "stage": 0,
  "env": {
    "development": {
      "plugins": ["react-transform"],
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }]
        }
      }
    }
  }
}
```

The Cerebral chrome extension is outstanding too.
'cerebral-boilerplate' plus Flow plus the testing setup in this project would be great, just saying.

**Comment by bebraw** [comment]
@davidmoshal Once I get "ok" to update the project, I'll make it use [babel-preset-react-hmre](https://www.npmjs.com/package/babel-preset-react-hmre). That takes care of the setup.

Here's the [hot loading bit](http://survivejs.com/webpack_react/webpack_and_react/#activating-hot-loading-for-development) of the book. I did the setup without the preset earlier, but that got rather messy. I think I'll add more about presets to the chapter, though, so you understand how to implement them, though.

**Comment by davidmoshal** [comment]
thanks, actually I have the book, but the link is helpful.    
Your snippet reminded be of the other issue with your .babelrc, namely: Flow.

The SurviveJS book recommends this for flow:     
- `"plugins": ["typecheck"]`

Babel [recommends](http://babeljs.io/docs/plugins/transform-flow-strip-types/):    
- `"plugins": ["transform-flow-strip-types"]`

I found that this worked:    
- `"plugins": ["typecheck", "syntax-flow", "transform-flow-strip-types"]`

So, would be great to know which is best to use!

**Comment by bebraw** [comment]
@davidmoshal GitHub lost your comment for some reason (downtime?). Here's the comment:

> thanks, actually I have the book, but the link is helpful.
> 
> Your snippet reminded be of the other issue with your .babelrc, namely: Flow.
> 
> The SurviveJS book recommends this for flow:
> 
> "plugins": ["typecheck"]
> Babel recommends:
> 
> "plugins": ["transform-flow-strip-types"]
> I found that this worked:
> 
> "plugins": ["typecheck", "syntax-flow", "transform-flow-strip-types"]
> So, would be great to know which is best to use!

Thanks for bringing this up.

The Flow bits are still quite bleeding edge, but I'll check it out and update the setup accordingly. :+1:

If I remember right, the typecheck plugin does branching based on environment already. But it's possible there's something missing. Esp. for production usage it makes sense to strip the typing.

**Comment by davidmoshal** [comment]
@bebraw - actually I deleted the comment when I realized that Babel React preset probably has all of those plugins:
- see:  https://babeljs.io/docs/plugins/preset-react/

Here is the relevant info: https://github.com/codemix/babel-plugin-typecheck

>  Important: This plugin has a dependency on babel-plugin-syntax-flow and babel-plugin-transform-flow-strip-types. Without syntax-flow, babel will be unable to parse the flow annotation syntax. Without transform-flow-strip-types, the type annotations will be included in the output which will make it unparsable by JS engines.
> 
> If you are not already using the babel-preset-react plugin, you must install those plugins and include them in your babel configuration (usually .babelrc). Put them after typecheck in the list, e.g.
> 
> ``` js
> {
>   "plugins": ["typecheck", "syntax-flow", "transform-flow-strip-types"]
> }
> ```

So, it's possible that you only need:

``` js
{
   "presets": ["react"],
   "plugins": ["typecheck"]
}
```
- I'm not sure whether the "typescheck" plugin is needed either if you have the react preset.

At any rate, I decided to go back to Typescript for now, better IDE (Webstorm) support at this time.

Separately, I decided against CerebralJS, for a couple of reasons:
- the Module concept in CerebralJS added an extra layer of boilerplate which I don't need (though would probably be useful on massive projects)
- the use of path strings in babel, which are spread out across numerous files and modules, doesn't work for my use-case (the cerebral docs recognize the pros and cons of this in their comparison to Redux).

So, despite having the best Chrome developer extension I've ever seen, Cerebral is just not going to work for me.

Dave

**Comment by bebraw** [comment]
@davidmoshal Ok, cool. Thanks for getting back to me!

**Comment by Guria** [comment]
@bebraw I think you can start transition. We have finished to deprecate stuff. App running`cerebral@0.33.16` without deprecation warnings should be compatible with upcoming `cerebral@0.34`.

But I am afraid we don't have clear upgrade path from `cerebral@0.19.4` used in this demo. So feel free to join us at [discord](https://discord.gg/0kIweV4bd2bwwsvH) and bother us if something not clear enough from docs.

**Comment by bebraw** [comment]
@Guria Ok, no probs. I'll look into it sometime this week most likely.

**Comment by christianalfoni** [comment]
I think this is fixed?

**Comment by bebraw** [comment]
@christianalfoni Not yet. Busy with release. Next week most likely.

**Comment by christianalfoni** [comment]
Oh, sorry :)

**Comment by bebraw** [comment]
@christianalfoni If you have time to debug, `deleteLane` has something weird going on. It's as if `state.unset(['data', 'lanes', input.id]);` doesn't do anything useful. A lane with an empty notes listing will still remain hanging. Not sure if that's my bug or upstream bug.

**Comment by christianalfoni** [comment]
All okay? Happy to help :)

**Comment by bebraw** [comment]
@christianalfoni There is only one problem. The current solution leaves `lanes.ids` hanging. Here's the relevant code from `modules/actions.js`:

``` javascript
export function deleteLane({input, state}) {
  const indexOfLane = state.get(['lanes', 'ids']).indexOf(input.id);

  // XXX: figure out why this leaves a reference hanging
  state.splice(['lanes', 'ids'], indexOfLane, 1);
  state.unset(['data', 'lanes', input.id]); // XXX: does this work???
};
```

That `state.splice(['lanes', 'ids'], indexOfLane, 1);` doesn't seem to do anything useful. Possibly I'm using the API wrong here and there's a better way to delete by given id.

The code should probably check against `-1` (no result) anyway.

**Comment by christianalfoni** [comment]
Hi there!

Yeah, `unset` should work. `state.unset(['data', 'lanes', input.id])`  :-) It does not work?

**Comment by bebraw** [comment]
Here's a trivial example:
1. Create a lane
2. Print model through Cerebral debug tools
3. Delete a lane
4. Print model through Cerebral debug tools

And result:

![screenshot 2016-02-21 21 00 24](https://cloud.githubusercontent.com/assets/166921/13204663/33fb2e54-d8de-11e5-8773-750e16bff95e.png)

So `splice` actually works. It's that `state.unset(['data', 'lanes', input.id]);` that doesn't do anything (fails silently) here.

**Comment by christianalfoni** [comment]
Is lanes an array? Unset is for objects :)

**Comment by bebraw** [comment]
`data.lanes` is an object for sure (lane id -> lane content). That's the weird thing here.

**Comment by christianalfoni** [comment]
Which version of `cerebral-model-baobab` is it?

**Comment by bebraw** [comment]
0.4.7, should be the latest.

Is there a debug flag or something to get more info out of baobab? I would love to understand what unset does exactly. Might as well debug this properly, though.

**Comment by christianalfoni** [comment]
It just uses the "unset" method on Baobab itself. http://www.cerebraljs.com/todomvc/ uses it as well, if you bring up the debugger, you see it running. Very strange. But I can have a rework of the demo, that API has changed a bit. Could check that out as well, would that be okay?

**Comment by bebraw** [comment]
Sure. Feel free to do any changes necessary. :+1: 

If you want, it might be cool to include the full app to your demos. Just link back here. Probably easy to set up.

**Comment by christianalfoni** [comment]
Cool, I will dive into it :) Let you know when I am done!

**Comment by christianalfoni** [comment]
Okay, the demo is now refactored and working. It was also running on the old debugger, so now you got a lot more insight :)

Mostly syntax and some structure changes. The bug you experienced was actually related to the "delete lane" button actually propagating up and also firing off a "laneUpdated" signal, which then caused an error. Could not update when it was deleted :) At least that is what I fixed after refactor.

Okay, goody, let me know if I can help with anything else!

**Comment by bebraw** [comment]
@christianalfoni Thanks! Esp. the new debugger looks great. Very handy!

The bug makes sense, yeah. Just missing `preventDefault`...

Thanks again! :+1:

**Comment by christianalfoni** [comment]
Awesome :) :+1:
